name: Publish package to GitHub Packages
on:
  push:
    branches: [master, sviluppo]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Publish package
        run: mvn clean deploy -s .m2/settings.xml -DskipTests --batch-mode --errors --fail-at-end --show-version
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
